### ISSUE TITLE
Failed to import package with error: Couldn't decompress package

### ISSUE THREAD

**Issue by dg3-ms** [flurry/unity-flurry-sdk#13]
Receive this error when trying to import the unity package. I tried from release 220 to 270. All gave the same error. I've tried in Unity versions 2018.3.7f1 and 2019.1.14f1. Thanks

**Comment by poting-oath** [comment]
I just tried both 2019.2.9f1 and 2020.1.1f1 without problem. Do you have the same issue for importing 1.0.0  to 2.1.0? As I remember, Unity made many backward incompatible changes very often.

**Comment by dg3-ms** [comment]
Sorry, noob mistake by me. I was 'saving link' from the Code page, rather than going into the file and downloading, which has resolved my issue! Thanks.

**Comment by poting-oath** [comment]
@dg3-ms Thanks for the report! You may just click on the links under the Installation section to download the package file. No need to right click to use the sub tasks.

**Installation**
Download the Flurry Unity package from **_[flurry-sdk-2.7.0.unitypackage](https://github.com/flurry/unity-flurry-sdk/raw/master/flurry-sdk-2.7.0.unitypackage)_**, or ### ### **_[flurry-sdk-2.7.0-push.unitypackage](https://github.com/flurry/unity-flurry-sdk/raw/master/flurry-sdk-2.7.0-push.unitypackage)_** if you want to use Flurry Push.
