### ISSUE TITLE
iOS 14 support for unity SDK

### ISSUE THREAD

**Issue by jmarisalandanan** [flurry/unity-flurry-sdk#14]
Hi! Any news on when iOS 14 support would be released for the Unity SDK? I see that support for iOS 14 has already been released for the iOS SDK. 

Thanks!

**Comment by flurrydev** [comment]
Hello @jmarisalandanan,

The Unity SDK is in testing and should be released in a day or two.

**Comment by poting-oath** [comment]
@jmarisalandanan Flurry Unity plugin 3.0.0 released!

Update for version 3.0.0
- Upgrade Flurry iOS SDK version to 11.0.0
- Support iOS 14 Compliant
- Support the iOS SKAdNetwork conversion
- Support opening Privacy Dashboard

**Comment by jmarisalandanan** [comment]
@poting-oath Thank you!

**Comment by jmarisalandanan** [comment]
Reopening due to recent development that Apple will delay ATT's implementation and found that 11.1.0 now has an option to make ATT optional. Any news for a Unity SDK update?

**Comment by flurrydev** [comment]
Hello @jmarisalandanan, We will release a new version of the plugin by the end of the week making ATT optional.

**Comment by mvl-illumix** [comment]
Hi @flurrydev 
Is it will it be sufficient to manually update the iOS libFlurry.a from 11.0.0 to the 11.1.0 version inside the Unity project? 
Thanks!

**Comment by flurrydev** [comment]
@jmarisalandanan @mvl-illumix 

_will it be sufficient to manually update the iOS libFlurry.a from 11.0.0 to the 11.1.0 version inside the Unity project?_

Yes this will resolve the issue.

**Comment by poting-oath** [comment]
Unity plugin 3.1.0 released:
- Upgrade Flurry Android SDK version to 12.7.0
- Upgrade Flurry iOS SDK version to 11.1.0
