### ISSUE TITLE
About unity plugin functions 

### ISSUE THREAD

**Issue by dh7300** [flurry/unity-flurry-sdk#15]
age and gender as in the example

Flurry.SetAge(33);
Flurry.SetGender(Flurry.Gender.Male);

I wrote the code below, but in the flurry dashboard, age and gender are showing as Unknown, can you tell me why?

**Comment by poting-oath** [comment]
@dh7300 It may be some delay. Do you still have this issue?

**Comment by dh7300** [comment]
@poting-oath 
on the dashboard
If "Usage -> App Activity -> Breakout:" is set to Gender or Age, the number I entered seems to be displayed.

but where i asked
When "Sessions -> User Journeys -> User1" is clicked, the Gender and Age of the user are displayed as Unknown. 
Country, Language, and Device are displayed normally.

**Comment by dh7300** [comment]
@poting-oath
And I have a question about Flurry Push. Should I create a new issue? Or I would like to know if I can ask additional questions to the current issue.

**Comment by poting-oath** [comment]
> @poting-oath
> And I have a question about Flurry Push. Should I create a new issue? Or I would like to know if I can ask additional questions to the current issue.

@dh7300 Please use separate ticket for different questions. Thanks!

**Comment by poting-oath** [comment]
> @poting-oath
> on the dashboard
> If "Usage -> App Activity -> Breakout:" is set to Gender or Age, the number I entered seems to be displayed.
> 
> but where i asked
> When "Sessions -> User Journeys -> User1" is clicked, the Gender and Age of the user are displayed as Unknown.
> Country, Language, and Device are displayed normally.

According to your description, this SDK plugin/wrapper works correctly by recording the values to the Flurry server.
For how Flurry UI is displaying the data, I will ask someone expert in this field to comment. Thanks!
