### ISSUE TITLE
NSKeyedUnarchiver validateAllowedClass log error

### ISSUE THREAD

**Issue by ausatovappcraft** [flurry/unity-flurry-sdk#16]
Hello, currently we have this in the log but analytics is sending correctly
We're using unity 2020.3.24f1 and 4.0.0 unity plugin version with il2cpp

*** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x1d9ce36e8) [/System/Library/Frameworks/Foundation.framework]' for key 'NS.keys', even though it was not explicitly included in the client allowed classes set: '{(

    "'FlurryDataSenderBlockInfo' (0x10abb6260) [/var/containers/Bundle/Application/9BD4B752-C3D3-4CF2-80BB-30EB23BBBF48/FoldMaster.app/Frameworks/UnityFramework.framework]",

    "'NSMutableDictionary' (0x1d9cd88e0) [/System/Library/Frameworks/CoreFoundation.framework]",

    "'NSArray' (0x1d9cd8a48) [/System/Library/Frameworks/CoreFoundation.framework]"

)}'. This will be disallowed in the future.

Should we do something with this?

**Comment by hantao-flurrydev** [comment]
@ausatovappcraft the fix will be available in the next release. Thanks!

**Comment by ausatovappcraft** [comment]
What date is the next release scheduled for?

**Comment by hantao-flurrydev** [comment]
Will be late next month or early March.

**Comment by poting-oath** [comment]
@ausatovappcraft Version 5.2.0 with the fix is released, please try. Thanks!
