### ISSUE TITLE
5.0.0 does not build in Xcode

### ISSUE THREAD

**Issue by andymads** [flurry/unity-flurry-sdk#17]
![Screenshot 2022-06-07 at 12 33 15](https://user-images.githubusercontent.com/15214465/172369571-23235165-ab0f-4d16-8482-e0aea11d15bd.png)

Using Unity 20230.3.26 and Xcode 13.2.1. Did a fresh build from Unity.

**Comment by poting-oath** [comment]
@andymads Starting from version 5.0.0, our plugin does not bundle the binaries as the previous releases did. Please try to clean the previous binaries and try again. Thanks!
I.e., remove the following files in the `Assets/Plugins/iOS` folder, then import the new 5.0.0.
```
Flurry+Event.h
Flurry.h
FlurryCCPA.h
FlurryConsent.h
FlurryMessaging.h
FlurrySKAdNetwork.h
FlurrySessionBuilder.h
FlurryUnityPlugin.h
FlurryUnityPlugin.mm
FlurryUserProperties.h
libFlurry.a
libFlurryMessaging.a
```

**Comment by poting-oath** [comment]
@andymads Version 5.2.0 with the fix is released, please try. Thanks!
