### ISSUE TITLE
IOException when building 5.1.0 for iOS (Appending build)

### ISSUE THREAD

**Issue by andymads** [flurry/unity-flurry-sdk#18]
IOException: Podfile already exists

Due to this line in Assets/Plugins/iOS/Editor/FlurryPodInstalling.cs

File.Copy(originalPodPath, podFilePath);

The optional third parameter to overwrite is required.

i.e.
File.Copy(originalPodPath, podFilePath,true);

**Comment by poting-oath** [comment]
@andymads Thanks for your feedback! We will include your fix in the next release.

**Comment by poting-oath** [comment]
@andymads Version 5.2.0 with the fix is released, please try. Thanks!
