### ISSUE TITLE
'Flurry_iOS_SDK/Flurry_iOS_SDK.h' file not found

### ISSUE THREAD

**Issue by sahilpma** [flurry/unity-flurry-sdk#19]
I am facing this issue.
Please help me with this.

Flurry SDK version 5.1.0
Unity Version 2022.1.14f1

![image](https://user-images.githubusercontent.com/38884892/188359279-377feaeb-e279-4a4d-9209-b0bfae4a8c7d.png)

I think there are few missing files.
![image](https://user-images.githubusercontent.com/38884892/188382887-ae1da685-4cad-403b-b609-4b596fb92254.png)

**Comment by sahilpma** [comment]
Anything solution to this?

**Comment by poting-oath** [comment]
@sahilpma Version 5.2.0 with the fix is released, please try. Thanks!

**Comment by sahilpma** [comment]
Thank you. Will try this out!
