### ISSUE TITLE
Missing or invalid signature

### ISSUE THREAD

**Issue by abhidec1** [flurry/unity-flurry-sdk#20]
When trying to validate the IPA to upload on appstoreconnect I am getting following error. 

Unable to process application at this time due to the following error: Missing or invalid signature. The bundle 'com.yahoo.Flurry-Config' at bundle path 'Payload/IceCreamInc..app/Frameworks/UnityFramework.framework/Flurry_Config.framework' is not signed using an Apple submission certificate..

Specs: 
Xcode : Version 13.4.1 (13F100)
OS : 12.2.1 (21D62) 
Unity : 2021.3.0f1
Flurry : 5.1.0

<img width="1008" alt="Screenshot 2022-09-06 at 10 47 37 PM" src="https://user-images.githubusercontent.com/32581521/188699250-929cf2d5-b704-408d-88e5-96a5d55e6631.png">

**Comment by naveenDayDreamzstudio** [comment]
same issue

**Comment by rob-nd** [comment]
Same issue here (Missing or invalid signature with 'com.yahoo.Flurry-Config') when attempting to upload

- XCode 14.0 (14A309)
- OS: 12.6 (21G115)
- Unity: 2020.3.37f1
- Flurry: 5.1.0

**Comment by poting-oath** [comment]
@abhidec1 @NaveenDDZ @rob-nd Version 5.2.0 with the fix is released, please try. Thanks!

**Comment by robl33** [comment]
@poting-oath our app validated and uploaded successfully with v5.2.0, thanks!
