### ISSUE TITLE
Is it possible to remove unused Flurry dependencies from build?

### ISSUE THREAD

**Issue by leni8ec** [flurry/unity-flurry-sdk#22]
Hello, if I only use the analytics service and don't use messages, push or ads.

Can I safely exclude these files from the build?

Android:
- `Assets\Plugins\Android\flurry-marketing.aar`
- `Assets\Plugins\Android\flurry-unity.aar`

iOS
- `Assets\Plugins\iOS\FlurryMessaging.h`
- `Assets\Plugins\iOS\libFlurryMessaging.a`

---

Based on [this](https://github.com/flurry/unity-flurry-sdk/issues/10#issuecomment-575274005) post

**Comment by poting-oath** [comment]
@leni8ec Yes, you can safely remove these file.
Android:

- Assets\Plugins\flurry-marketing.aar
- Assets\Plugins\Androidflurry-unity.aar

iOS

- Assets\Plugins\iOS\FlurryMessaging.h
- Assets\Plugins\iOS\libFlurryMessaging.a
