### ISSUE TITLE
Deprecated API -UIWebView

### ISSUE THREAD

**Issue by lion-hoopu** [flurry/unity-flurry-sdk#7]
After submitting my app (which uses FlurrySDK) to the AppStore, I've received the following message:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I just see the flurry for iOS resolved this problem. but unity version still go wrong.

There is any plan to get rid of this? I am afraid, Apple will not accept the usage of UIWebView soon.

Thanks in advance,
Lion

**Comment by flurrydev** [comment]
Hello Lion,

UIWebView has been removed from Flurry's SDK and our Unity Plugin version 2.2+ is up to date with this change. Thank you for reporting the issue.

**Comment by lion-hoopu** [comment]
Thank you.
